dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  adaptive_components: ^0.0.10
  adaptive_navigation: ^0.0.10
  animations: ^2.0.11
  cupertino_icons: ^1.0.6
  dynamic_color: ^1.6.9
  go_router: ^13.0.1
  http: ^1.2.0
  intl: ^0.18.1
  shared_preferences: ^2.2.2
  two_dimensional_scrollables: ^0.0.6
  url_launcher: ^6.2.2

description: Open Source Mathematics Engine

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^3.0.1

environment:
  sdk: '>=3.0.0 <6.0.0'

flutter:
  assets:
    - lib/assets/
    - lib/assets/icons/
  uses-material-design: true

name: calculate_engine
publish_to: 'none'
version: 0.2.0